services:
  - type: static
    name: angular-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/specialist-app
    routes:
      - type: rewrite
        source: /*
        destination: /index.html